// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVt15JkTQu4AsjDV9wZWmf07zosml3XD0',
    appId: '1:1085144778387:web:320a6ec47e981d2011af66',
    messagingSenderId: '1085144778387',
    projectId: 'rashtra-veer',
    authDomain: 'rashtra-veer.firebaseapp.com',
    storageBucket: 'rashtra-veer.firebasestorage.app',
    measurementId: 'G-MF3L5QPMKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpNfIed6icmceWSYmOW9cSQcf8LdanqQ',
    appId: '1:1085144778387:android:cc345a200e559afc11af66',
    messagingSenderId: '1085144778387',
    projectId: 'rashtra-veer',
    storageBucket: 'rashtra-veer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEDvQNtfqkdlyQyTZ5vqeJ1l-N-ciB6Q',
    appId: '1:1085144778387:ios:23343ba0083f59aa11af66',
    messagingSenderId: '1085144778387',
    projectId: 'rashtra-veer',
    storageBucket: 'rashtra-veer.firebasestorage.app',
    iosBundleId: 'com.example.rashtraveer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEDvQNtfqkdlyQyTZ5vqeJ1l-N-ciB6Q',
    appId: '1:1085144778387:ios:23343ba0083f59aa11af66',
    messagingSenderId: '1085144778387',
    projectId: 'rashtra-veer',
    storageBucket: 'rashtra-veer.firebasestorage.app',
    iosBundleId: 'com.example.rashtraveer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVt15JkTQu4AsjDV9wZWmf07zosml3XD0',
    appId: '1:1085144778387:web:417c60c79e4c00cc11af66',
    messagingSenderId: '1085144778387',
    projectId: 'rashtra-veer',
    authDomain: 'rashtra-veer.firebaseapp.com',
    storageBucket: 'rashtra-veer.firebasestorage.app',
    measurementId: 'G-657YH0F4KE',
  );
}
